---
title: "Gridded GSDR analysis"
author: "Tony Rafter"
date: "2024-06-27"
output: 
  html_notebook:
      theme: yeti
  html_document:
    df_print: paged
    toc: yes
    toc_float:
      collapsed: true
  prettydoc::html_pretty:
    theme: leonids

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
library(mapdata)
# library(patchwork)
# library(timeplyr)
# library(ggrepel)
# library(broom)
# library(gt)
# library(knitr)
# library(scales)
# library(zoo)
# library(Kendall)
library(ncdf4)
```

## Gridded GSDR

The GSDR data consists of a 1 degree grid of extreme rainfall indices, with the values for each cell derived from station observations lying within that grid cell.


```{r load sample netcdf}
gridded_rx1hr <- ncdf4::nc_open("C:/Users/raf018/OneDrive - CSIRO/Working/PhD/Observations/GSDR-I/Dataset/Grids/TimeSeries/Annual/Annual_Rx1hr.nc", readunlim = TRUE)

# set lon-lat limits for Australia
aus_lon_limits <- c(112, 156)
aus_lat_limits <- c(-45, -10)



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
